name: "I2C Test pcf8575"
description: "i2c pcf8575"
version: "1.0.22"
slug: "i2c_test"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
log_level: info
startup: services
privileged:
  - SYS_ADMIN
devices:
  - /dev/i2c-1
device_tree: true
